"""Criação inicial das tabelas com env.py corrigido

Revision ID: 41389e09d977
Revises: 
Create Date: 2025-10-17 16:47:27.887122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41389e09d977'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galgos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sire', sa.String(length=150), nullable=True),
    sa.Column('dam', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'data_nascimento', 'sire', 'dam', name='uq_galgo_unico')
    )
    op.create_table('pistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('treinadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('corridas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pista_id', sa.Integer(), nullable=False),
    sa.Column('horario', sa.String(length=10), nullable=False),
    sa.Column('data_corrida', sa.Date(), nullable=False),
    sa.Column('numero_corrida', sa.String(length=10), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=True),
    sa.Column('distancia', sa.Integer(), nullable=True),
    sa.Column('premios', sa.String(length=100), nullable=True),
    sa.Column('perfil_pista', sa.Text(), nullable=True),
    sa.Column('favoritos_tf', sa.Text(), nullable=True),
    sa.Column('favoritos_gh', sa.String(length=20), nullable=True),
    sa.Column('cartao_corrida', sa.Text(), nullable=True),
    sa.Column('href_tf', sa.String(length=500), nullable=True),
    sa.Column('href_gh', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['pista_id'], ['pistas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('href_gh'),
    sa.UniqueConstraint('href_tf'),
    sa.UniqueConstraint('pista_id', 'data_corrida', 'horario', 'numero_corrida', name='uq_corrida_unica')
    )
    op.create_table('historico_corridas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('galgo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('tipo_corrida', sa.String(length=10), nullable=True),
    sa.Column('pista_id', sa.Integer(), nullable=True),
    sa.Column('distancia', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=20), nullable=True),
    sa.Column('eye', sa.String(length=10), nullable=True),
    sa.Column('proxy', sa.String(length=10), nullable=True),
    sa.Column('faixa', sa.Integer(), nullable=True),
    sa.Column('tf_sec', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bend', sa.Integer(), nullable=True),
    sa.Column('fin', sa.Integer(), nullable=True),
    sa.Column('tf_going', sa.String(length=20), nullable=True),
    sa.Column('isp', sa.String(length=20), nullable=True),
    sa.Column('tf_time', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sec_rtg', sa.String(length=10), nullable=True),
    sa.Column('rtg', sa.String(length=10), nullable=True),
    sa.Column('observacoes_tf', sa.Text(), nullable=True),
    sa.Column('observacoes_gh', sa.Text(), nullable=True),
    sa.Column('split', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('btn_by', sa.String(length=15), nullable=True),
    sa.Column('win_sec', sa.String(length=20), nullable=True),
    sa.Column('wntm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gng', sa.String(length=20), nullable=True),
    sa.Column('wght', sa.String(length=20), nullable=True),
    sa.Column('caltm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['galgo_id'], ['galgos.id'], ),
    sa.ForeignKeyConstraint(['pista_id'], ['pistas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('galgo_id', 'data', 'pista_id', 'distancia', name='uq_historico_unico')
    )
    op.create_table('corrida_historico_associacao',
    sa.Column('corrida_id', sa.Integer(), nullable=False),
    sa.Column('historico_corrida_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['corrida_id'], ['corridas.id'], ),
    sa.ForeignKeyConstraint(['historico_corrida_id'], ['historico_corridas.id'], ),
    sa.PrimaryKeyConstraint('corrida_id', 'historico_corrida_id')
    )
    op.create_table('participacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corrida_id', sa.Integer(), nullable=False),
    sa.Column('galgo_id', sa.Integer(), nullable=False),
    sa.Column('treinador_id', sa.Integer(), nullable=True),
    sa.Column('faixa', sa.Integer(), nullable=True),
    sa.Column('win_rec', sa.String(length=20), nullable=True),
    sa.Column('trap_rec', sa.String(length=20), nullable=True),
    sa.Column('mstr', sa.Integer(), nullable=True),
    sa.Column('sect', sa.Integer(), nullable=True),
    sa.Column('posicoes_anteriores', sa.String(length=50), nullable=True),
    sa.Column('strike_rate', sa.String(length=10), nullable=True),
    sa.Column('seed', sa.String(length=20), nullable=True),
    sa.Column('comentario_tf', sa.Text(), nullable=True),
    sa.Column('comentario_gh', sa.Text(), nullable=True),
    sa.Column('sp_forecast', sa.String(length=20), nullable=True),
    sa.Column('top_speed', sa.String(length=20), nullable=True),
    sa.Column('brt', sa.String(length=20), nullable=True),
    sa.Column('brt_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['corrida_id'], ['corridas.id'], ),
    sa.ForeignKeyConstraint(['galgo_id'], ['galgos.id'], ),
    sa.ForeignKeyConstraint(['treinador_id'], ['treinadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corrida_id', 'galgo_id', name='uq_participacao_unica')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participacoes')
    op.drop_table('corrida_historico_associacao')
    op.drop_table('historico_corridas')
    op.drop_table('corridas')
    op.drop_table('treinadores')
    op.drop_table('pistas')
    op.drop_table('galgos')
    # ### end Alembic commands ###
