"""Adiciona colunas video_href_raw e video_status em HistoricoCorrida

Revision ID: b6fc66d8281d
Revises: 41389e09d977
Create Date: 2025-10-24 21:09:10.292887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6fc66d8281d'
down_revision: Union[str, Sequence[str], None] = '41389e09d977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historico_corridas', sa.Column('video_href_raw', sa.String(length=500), nullable=True))
    op.add_column('historico_corridas', sa.Column('video_status', sa.String(length=20), nullable=False))
    op.alter_column('historico_corridas', 'faixa',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_historico_corridas_video_status'), 'historico_corridas', ['video_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_corridas_video_status'), table_name='historico_corridas')
    op.alter_column('historico_corridas', 'faixa',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('historico_corridas', 'video_status')
    op.drop_column('historico_corridas', 'video_href_raw')
    # ### end Alembic commands ###
